# 一、ndarray
## 1. ndarray特性
#### 多维性

In [2]:
import numpy as np

In [ ]:
arr = np.array(5) #创建了一个0维的数组
print(arr)
print(arr.ndim) #输出数组的维度

5
0


In [ ]:
arr = np.array([1,2,3,4,5]) #创建了一个1维的数组
print(arr)
print(f"数组的维度是:{arr.ndim}") #输出数组的维度

[1 2 3 4 5]
数组的维度是:1


In [9]:
arr = np.array([[1,2,3,4,5],[5,4,3,2,1]]) #创建了一个1维的数组
print(arr)
print(f"数组的维度是:{arr.ndim}") #输出数组的维度

[[1 2 3 4 5]
 [5 4 3 2 1]]
数组的维度是:2


## 同质性

In [10]:
arr = np.array([1,"hello"]) #创建了一个1维的数组
print(arr)

['1' 'hello']


In [ ]:
arr = np.array([1,2.5]) #创建了一个1维的数组
print(arr) # 自动修改为统一数据类型

[1.  2.5]


## 主要属性
- shape
- ndim
- size
- dtype

In [13]:
arr = np.array(5)
print(arr)
print(f"数组的形状{arr.shape}")
print(f"数组的维度{arr.ndim}")
print(f"数组的个数{arr.size}")

5
数组的形状()
数组的维度0
数组的个数1


In [14]:
arr = np.array([1,2,3])
print(arr)
print(f"数组的形状{arr.shape}")
print(f"数组的维度{arr.ndim}")
print(f"数组的个数{arr.size}")

[1 2 3]
数组的形状(3,)
数组的维度1
数组的个数3


In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(f"数组的形状{arr.shape}")
print(f"数组的维度{arr.ndim}")
print(f"数组的个数{arr.size}")
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
数组的形状(2, 3)
数组的维度2
数组的个数6
int64


### 创建方式 

In [18]:
#基础创建方式
arr = np.array([1,2,3],dtype=float)
print(arr)

[1. 2. 3.]


In [19]:
#copy
arr1 = np.copy(arr)
arr1[0] = 8
print(arr1)

[8. 2. 3.]


In [21]:
# 预定义
# 全0 
arr = np.zeros((2,3)) #默认float类型
print(arr)
# 全1
arr1 = np.ones((3,))
print(arr1)
# 未初始化
arr2 = np.empty((3,3))
print(arr2)
# 固定值
arr3 = np.full((2,2),2026)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23048521e-307 2.22526399e-307 6.23053614e-307]
 [7.56592338e-307 9.34588060e-307 3.62651150e-317]]
[[2026 2026]
 [2026 2026]]


In [22]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr1 = np.arange(0,101,25)
arr2 = np.logspace(0,4,3,base = 2) #对数生成
arr3 = np.linspace(0,100,5,dtype= int ) # 生成多少个
print(arr1)
print(arr2)
print(arr3)

[  0  25  50  75 100]
[ 1.  4. 16.]
[  0  25  50  75 100]


In [30]:
# 生成矩阵
# 单位矩阵
arr = np.eye(3,4,dtype= int)
print(arr)
# 对角矩阵
arr1 = np.diag([1,2,3])
print(arr1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [33]:
# 生成随机数组
# 生成0，1的随机浮点数
arr = np.random.rand(2,3)
print(arr)
# 生成指定范围
arr1 = np.random.uniform(3,6,(2,3))
print(arr1)
# 生成整数
arr2 = np.random.randint(3,30,(2,3))
print(arr2)
# 生成随机数列（正态分布
arr3 = np.random.randint(3,30,(2,3))
print(arr3)

[[0.83256204 0.82408934 0.86954528]
 [0.28325637 0.30284377 0.40576449]]
[[4.34865272 4.37740062 3.11586033]
 [3.63648985 5.05021265 5.30144806]]
[[28 27 28]
 [11 19 11]]
[[14 16  4]
 [ 8 28 25]]


## 索引和切片

In [34]:
arr = np.random.randint(1,100,20)
print(arr)

[37 46 76 33 54 52 29 91 44 69 14 63 94  5 57 38 36 73 89 92]


In [35]:
print(arr[10])
print(arr[2:5])
print(arr[slice(2,5)])

14
[76 33 54]
[76 33 54]


### ndarry的运算

In [ ]:
# 矩阵的乘法用@

### numpy的基本数学函数

In [36]:
#计算平方根
print(np.sqrt(9))

3.0


### 统计函数

In [38]:
# 求和
arr = np.random.randint(1,20,8)
print(arr)

[13 17 18  8 16  2  2  5]


In [47]:
# 求和 
print(np.sum(arr))
# 计算平均值
print(np.mean(arr))
# 计算中位数
print(np.median(arr))
# 计算标准差和方差
print(np.var(arr))
print(np.std(arr))
# 最值及其位置
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))
# 分位数
print(np.percentile(arr,0))
# 累计的和 积
print(np.cumsum(arr))
print(np.cumprod(arr))

81
10.125
10.5
39.359375
6.273705045664802
18 2
2 5
2.0
[13 30 48 56 72 74 76 81]
[      13      221     3978    31824   509184  1018368  2036736 10183680]


## 比较函数

In [4]:
# 是否大于
print(np.greater([1,2,3,4],2))
#是否小于
print(np.less([1,2,3,4],2))
# 是否等于
print(np.equal([1,2,3,4],[2,2,2,2]))
# 逻辑与 逻辑或
print(np.logical_and([1,0],[1,1]))
# 是否有一个元素
print(np.any([0,0,0,1]))
print(np.all([1,1,0]))
# 自定义条件
arr = np.array([1,2,3,4,5])
print(np.where(arr > 3))

[False False  True  True]
[ True False False False]
[False  True False False]
[ True False]
True
False
(array([3, 4]),)


题目 1:温度数据分析
某城市一周的最高气温('℃)为[28,30,29,31,32,30,29]。
- 计算平均气温、最高气温和最低气温。
- 找出气温超过 30℃ 的天数。

In [5]:
temp = np.array([28,30,29,31,32,30,29])
aver_temp = np.average(temp)
max_temp = np.max(temp)
min_temp = np.min(temp)
days = np.argwhere(temp > 30)
print(f"平均气温{aver_temp:.3f}、最高气温{max_temp}和最低气温{min_temp}，气温超过 30℃ 的天数为{days}")

平均气温29.857、最高气温32和最低气温28，气温超过 30℃ 的天数为[[3]
 [4]]


题目 2:学生成绩统计
某班级 5 名学生的数学成绩为[85,90,78,92,88]。
- 计算成绩的平均分、中位数和标准差。
- 将成绩转换为百分制(假设满分为 100)。

In [9]:
score = np.array([85,90,78,92,88])
print(f"成绩的平均分{np.mean(score):.1f}、中位数{np.median(score)}和标准差{np.std(score):.3f}")
print(score / 10 )

成绩的平均分86.6、中位数88.0和标准差4.883
[8.5 9.  7.8 9.2 8.8]


题目 3:矩阵运算
给定矩阵 A=[[1,2],[3,4]]和 B=[[5,6],[7,8]]。
:- 计算 A+B和A*B(逐元素乘法)。
-计算 A和 B 的矩阵乘法(点积)。

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


题目 4:随机数据生成
生成一个(3,4)的随机整数数组,范围[0,10)。
- 计算每列的最大值和每行的最小值。
- 将数组中的所有奇数替换为 -1。|

In [ ]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
print(f"每行的最大值为{np.max(arr,axis= 1)},最小值为{np.min(arr,axis= 1)}") # 1是列 0是行
print(f"每列的最大值为{np.max(arr,axis= 0)},最小值为{np.max(arr,axis= 0)}")
print(np.where(arr%2 == 0,arr,-1))  # where 本身不改变矩阵

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每行的最大值为[5 9 7],最小值为[0 3 2]
每列的最大值为[7 9 7 6],最小值为[7 9 7 6]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


题目 5:数组变形
创建一个 1到12 的一维数组,并转换为(3,4)的二维数组。
- 计算每行的和与每列的平均值。
- 将数组展平为一维数组。

In [27]:
arr = np.arange(1,13,dtype=int)
arr = np.split(arr,3)
print(arr)
print(f"每行的和与每列的平均值为{np.sum(arr,axis = 1)},{np.mean(arr,axis=0)}")
print(np.concatenate(arr))

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
每行的和与每列的平均值为[10 26 42],[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


题目 7:统计函数应用
某公司 6 个月的销售额(万元)为[120,135,110,125,130,140]。
- 计算销售额的总和、均值和方差。
- 找出销售额最高的月份和最低的月份。

In [29]:
sales = np.array([120,135,110,125,130,140])
print(f"销售额的总和{np.sum(sales):.1f}、均值{np.mean(sales):.1f}和方差{np.var(sales):.1f}")
print(f"销售额最高的月份{np.argmax(sales)+1}和最低的月份{np.argmin(sales)+1}")

销售额的总和760.0、均值126.7和方差97.2
销售额最高的月份6和最低的月份3


题目 8:数组拼接
给定 A=[1,2,3]和 B=[4,5,6]。
-将A和 B 水平拼接为一个新数组。
-将A和 B 垂直拼接为一个新数组。

In [33]:
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.concatenate((A,B))
print(C)
C = np.stack((A,B))
print(C)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


""
给定数组 [2,1,2,3,1,4,3]。
- 找出数组中的唯一值并排序。
- 计算每个唯一值出现的次数。

题目 9:唯一值与排序

In [ ]:
arr = np.array([2,1,2,3,1,4,3])
print(np.sort(np.unique(arr)))
print(np.sort(np.unique(arr)))

[1 2 3 4]



题目 20:综合应用
某商店 5 天的销售额(万元)和成本(万元)如下:
销售额:[20,25,22,30,28]
成本:[15,18,16,22,20]
- 计算每天的利润(销售额- 成本)。
-计算利润的平均值和标准差。
- 找出利润最高的天数。


In [36]:
sales = np.array([20,25,22,30,28])
ben = np.array([15,18,16,22,20])
profit = sales - ben
print(f"每天的利润是{sales-ben}")
print(f"利润的平均值为{np.mean(profit)},标准差为{np.std(profit)}")
print(f"利润最高的天数是{np.argmax(profit) + 1}")


每天的利润是[5 7 6 8 8]
利润的平均值为6.8,标准差为1.16619037896906
利润最高的天数是4
